### ISSUE TITLE
Chain of trust failing

### ISSUE THREAD

**Issue by tileandrewarifin** [etsy/applepay-php#9]
I am using the apple_pay.cer that I downloaded from the Apple Developer Portal. This is the error I get when I execute `openssl verify -verbose -CAfile root.pem int_merch.pem`

Error Message:
`int_merch.pem: /CN=Apple Application Integration CA - G3/OU=Apple Certification Authority/O=Apple Inc./C=US
error 7 at 0 depth lookup:certificate signature failure
98898:error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/crypto/asn1/a_verify.c:164:`

**Comment by adsr** [comment]
@tileandrewarifin Do you mind summarizing what you found? (OpenSSL version I'm guessing?) Thanks

**Comment by tileandrewarifin** [comment]
Yes, this was an issue with OpenSSL version.
